//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassFileManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class zData : global::System.Configuration.ApplicationSettingsBase {
        
        private static zData defaultInstance = ((zData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new zData())));
        
        public static zData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LoadedFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LoadedFiles"]));
            }
            set {
                this["LoadedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Recurse {
            get {
                return ((bool)(this["Recurse"]));
            }
            set {
                this["Recurse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Scale {
            get {
                return ((bool)(this["Scale"]));
            }
            set {
                this["Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Size Size {
            get {
                return ((global::System.Drawing.Size)(this["Size"]));
            }
            set {
                this["Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ExtensionList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExtensionList"]));
            }
            set {
                this["ExtensionList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtensionListRegex {
            get {
                return ((string)(this["ExtensionListRegex"]));
            }
            set {
                this["ExtensionListRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FilesChosen {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilesChosen"]));
            }
            set {
                this["FilesChosen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SortedLoadedFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SortedLoadedFiles"]));
            }
            set {
                this["SortedLoadedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Filter {
            get {
                return ((bool)(this["Filter"]));
            }
            set {
                this["Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Windows Media Player")]
        public string PreferredPlayer {
            get {
                return ((string)(this["PreferredPlayer"]));
            }
            set {
                this["PreferredPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VLCLoc {
            get {
                return ((string)(this["VLCLoc"]));
            }
            set {
                this["VLCLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WMPLoc {
            get {
                return ((string)(this["WMPLoc"]));
            }
            set {
                this["WMPLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileNotFound {
            get {
                return ((bool)(this["FileNotFound"]));
            }
            set {
                this["FileNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FileChooserBG {
            get {
                return ((global::System.Drawing.Color)(this["FileChooserBG"]));
            }
            set {
                this["FileChooserBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FileChooserFore {
            get {
                return ((global::System.Drawing.Color)(this["FileChooserFore"]));
            }
            set {
                this["FileChooserFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonBG {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBG"]));
            }
            set {
                this["ButtonBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonFore {
            get {
                return ((global::System.Drawing.Color)(this["ButtonFore"]));
            }
            set {
                this["ButtonFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TextBoxBG {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxBG"]));
            }
            set {
                this["TextBoxBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TextBoxFore {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxFore"]));
            }
            set {
                this["TextBoxFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TextFore {
            get {
                return ((global::System.Drawing.Color)(this["TextFore"]));
            }
            set {
                this["TextFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BG {
            get {
                return ((global::System.Drawing.Color)(this["BG"]));
            }
            set {
                this["BG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::System.Windows.Forms.FlatStyle ButtonFlatStyle {
            get {
                return ((global::System.Windows.Forms.FlatStyle)(this["ButtonFlatStyle"]));
            }
            set {
                this["ButtonFlatStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fixed3D")]
        public global::System.Windows.Forms.BorderStyle PanelBorderStyle {
            get {
                return ((global::System.Windows.Forms.BorderStyle)(this["PanelBorderStyle"]));
            }
            set {
                this["PanelBorderStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ButtonImageStyle {
            get {
                return ((string)(this["ButtonImageStyle"]));
            }
            set {
                this["ButtonImageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ButtonUseVisualStyles {
            get {
                return ((bool)(this["ButtonUseVisualStyles"]));
            }
            set {
                this["ButtonUseVisualStyles"] = value;
            }
        }
    }
}
